---
# handlers file for dockers
- name: Restart bind9
  ansible.builtin.service:
    name: bind9
    state: restarted
#
- name: Restart dhcp
  ansible.builtin.service:
    name: isc-dhcp-server
    state: restarted
#
- name: Restart networking
  ansible.builtin.service:
    name: networking
    state: restarted