
- name: Job 12 | Install ansible package using apt
  apt:
    name: "{{item}}"
    state: present
  loop:
    "{{apt_ansbl_pckg_lst}}"
  when: instl_ansbl_pckg
  #tags: test
#
- name: Job 13 | Install ansible package using pip
  ansible.builtin.pip:
    name: "{{item}}"  
    state: present
  loop:
    "{{pip_ansbl_pckg_lst}}"
  when: instl_ansbl_pckg
  #tags: test

