
- name: SSH | Update resolv temp to allow update.
  lineinfile:
    dest: /etc/resolv.conf
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
    #validate: 'sshd -t -f %s'
  with_items:
    - regexp: "^nameserver 1.1.1.1"
      line: "nameserver 1.1.1.1"
    # - regexp: "^PermitRootLogin"
    #   line: "PermitRootLogin no"
    # - regexp: "^Port"
    #   line: "Port 22"
    # - regexp: "^PubkeyAuthentication"
    #   line: "PubkeyAuthentication yes"
    # - regexp: "^ChallengeResponseAuthentication"
    #   line: "ChallengeResponseAuthentication no"
    # - regexp: "^PermitEmptyPasswords"
    #   line: "PermitEmptyPasswords no"    
    # - regexp: "^AllowAgentForwarding"
    #   line: "AllowAgentForwarding yes"         
  #notify: restart ssh
  when: addresolv
  tags: 
    - #test
