---
collections:
  - name: community.routeros
    version: ">=3.22.0,<4.0.0"
  - name: ansible.netcommon
    version: ">=7.2.0,<8.0.0"
  - name: ansible.utils
    version: ">=5.1.2,<6.0.0"
  - name: community.general
    version: ">=8.6.0,<9.0.0"
  - name: ansible.posix
    version: ">=1.5.4,<2.0.0"


# ansible-galaxy collection install -r collections/requirements.yml
