version: '3.3'
services:
    portainer-ce:
        #replica: 3
        container_name: portainer
        ports:
            - '8000:8000'
            - '9000:9000'
            - '9443:9443'
        volumes:
            - '/var/run/docker.sock:/var/run/docker.sock'
            - './docker/portainer:/data:rw'
        restart: always
        image: portainer/portainer-ce:latest