- name: APT | STARTING run-apt.yml
  hosts: allservers
  ignore_errors: true
  ignore_unreachable: true
  # remote_user: root
  remote_user: ibrahim
  become: true
  become_user: root
  roles:
    - apt

# - name: APT | STARTING run-apt.yml - LOCALHOST
#   hosts: local
#   ignore_errors: true
#   ignore_unreachable: true
#   connection: local
#   # remote_user: root
#   remote_user: ibrahim
#   become: true
#   become_user: root
#   roles:
#     - apt

# complete and working
