---
# tasks file for anydesk

- name: Job 01 | Import AnyDesk GPG Key
  apt_key:
    url: https://keys.anydesk.com/repos/DEB-GPG-KEY
    state: present 
    validate_certs: yes
  when: instl_anydesk
#  
- name: Job 02 | Add AnyDesk Repo
  apt_repository:
    repo: "deb http://deb.anydesk.com/ all main"
    state: present 
    mode: 0644 
    update_cache: yes 
    validate_certs: yes 
  when: instl_anydesk
#  
- name: Job 03 | Install AnyDesk Package
  apt:
    pkg: "{{item}}"
    state: present
  loop:
    - anydesk
  when: instl_anydesk
