---
#
- name: Job 01 | import task lockdown
  ansible.builtin.import_tasks:
    file: lockdown.yml
  tags:
    - #test  
#
- name: Job 02 | import task allowRootLogin
  ansible.builtin.import_tasks:
    file: allowrootlogin.yml
  when: allowrootlogin
  tags:
    - allowrootlogin
    - #test  
