---
- name: Debconf set default locale Ubuntu
  ansible.builtin.debconf:
    name: locales
    question: locales/default_environment_locale
    value: en_GB.UTF-8
    vtype: select
  #when: ansible_distribution == 'Ubuntu'

- name: Locales package present Ubuntu
  ansible.builtin.apt:
    pkg:
      - locales
  #when: ansible_distribution == 'Ubuntu'

- name: set as default locale Ubuntu
  ansible.builtin.command: localectl set-locale LANG=en_GB.UTF-8
  #when: ansible_distribution == 'Ubuntu'

- name: set as default x11-keymap Ubuntu
  ansible.builtin.command: localectl --no-convert set-x11-keymap de
  #when: ansible_distribution == 'Ubuntu'

- name: create vconsole.conf for VC Keymap Ubuntu
  ansible.builtin.copy:
    dest: /etc/vconsole.conf
    content: |
      KEYMAP=de
  #when: ansible_distribution == 'Ubuntu'
###########
- name: Get existing debconf values for locales 
  ansible.builtin.debconf:
    name: locales 
  register: locale_dcnf

- name: Set a variable for the current locales
  ansible.builtin.set_fact:
    locale_dcnf_locale: "{{ locale_dcnf | community.general.json_query(locale_dcnf_jpq) }}"
  vars:
    locale_dcnf_jpq: 'current.["locales/default_environment_locale"]|[0]'
  
- name: Debug existing debconf value for locales/default_environment_locale
  ansible.builtin.debug:
    var: locale_dcnf_locale
  
- name: Debconf set default locale
  ansible.builtin.debconf:
    name: locales 
    question: locales/default_environment_locale
    value: "{{ locale_lang }}"
    vtype: select
  when: locale_dcnf_locale != locale_lang