---
- name: Job 01 | import task others
  ansible.builtin.import_tasks:
    file: misc.yml
  #when: apt_host_pckg_lst | contains bind9
  tags: 
    - #test
#
# - name: Job 02 | import task myiptables
#   ansible.builtin.import_tasks:
#     file: myiptable.yml
#   #when: apt_host_pckg_lst | contains bind9
#   tags: 
#     - #test
#
- name: Job 03 | import task meryem
  ansible.builtin.import_tasks:
    file: meryem.yml
  #when: apt_host_pckg_lst | contains bind9
  tags: 
    - meryem
    - #test