
- name: Crontab | cronjob crntb_actvt_crnjbs_mrym
  cron:
    name: "Starting CI/CD cronjob meryem"
    user: ibrahim
    job: "bash /opt/crontab/meryem.sh"
    state: present
    backup: False 
    minute: "*/1" # Minute when the job should run ( 0-59, *, */2, etc )
    hour: "*" # Hour when the job should run ( 0-23, *, */2, etc )
    day: "*" # Day of the month the job should run ( 1-31, *, */2, etc )
    month: "*" # Month of the year the job should run ( 1-12, *, */2, etc )
    weekday: "*" # Day of the week that the job should run ( 0-6 for Sunday-Saturday, *, etc )
    disabled: False # If the job should be disabled (commented out) in the crontab. Only has effect if C(state=present).
  when: crntb_actvt_crnjbs_mrym
  tags: 
    - meryem
    - #test
#
# does not work
- name: Crontab | /*REMOVE*/ cronjob not crntb_actvt_crnjbs_mrym
  cron:
    name: "REMOVING CI/CD cronjob meryem"
    user: ibrahim
    job: "bash /opt/crontab/meryem.sh"
    state: absent
    backup: False 
    minute: "*/1" # Minute when the job should run ( 0-59, *, */2, etc )
    hour: "*" # Hour when the job should run ( 0-23, *, */2, etc )
    day: "*" # Day of the month the job should run ( 1-31, *, */2, etc )
    month: "*" # Month of the year the job should run ( 1-12, *, */2, etc )
    weekday: "*" # Day of the week that the job should run ( 0-6 for Sunday-Saturday, *, etc )
    disabled: True # If the job should be disabled (commented out) in the crontab. Only has effect if C(state=present).
  when: not crntb_actvt_crnjbs_mrym
  tags: 
    - meryem
    - #test