---
# tasks file for bashrc
- name: Job 01 | copy .bashrc file to ibrahim
  copy:
    src: "files/home/ibrahim/"
    dest: "~/"
    owner: ibrahim
    group: ibrahim
    mode: 0744
  when: ansible_os_family == 'Debian'
#
- name: Job 02 | copy .ssh/config file to ibrahim
  copy:
    src: "files/home/.ssh/config"
    dest: "~/.ssh/"
    owner: ibrahim
    group: ibrahim
    mode: 0644
  when: ansible_os_family == 'Debian'
#
- name: Job 03 | copy .bashrc file to root
  copy:
    src: "files/home/ibrahim/"
    dest: "/root/"
    owner: root
    group: root
    mode: 0744
  when: ansible_os_family == 'Debian'
#
- name: Job 04 | copy .ssh/config file to root
  copy:
    src: "files/home/.ssh/config"
    dest: "~/.ssh/"
    owner: root
    group: root
    mode: 0644
  when: ansible_os_family == 'Debian'