---
# tasks file for configs
- name: Job 01 | import task anydesk
  ansible.builtin.import_tasks:
    file: anydesk.yml
#
- name: Job 05 | Copy root folder to target host that matches "ansible_hostname"
  copy:
    src: "files/{{ansible_hostname}}/root"
    dest: "/"
    owner: root
    group: root
    mode: 0700
  when: ansible_hostname != 'virthost01'
#
- name: Job 05.1 | Copy global/etc to etc on each linux server
  copy:
    src: "files/global/etc/"
    dest: "/etc/"
    owner: root
    group: root
    mode: 0700
  when: ansible_os_family == 'Debian'
#
- name: Job 06 | import task bind
  ansible.builtin.import_tasks:
    file: bind.yml
  #when: apt_host_pckg_lst | contains bind9
  tags: 
    - dns

- name: Job 07 | import task interfaces
  ansible.builtin.import_tasks:
    file: interfaces.yml
  #when: apt_host_pckg_lst | contains bind9
#
- name: Job 08 | import task symlink
  ansible.builtin.import_tasks:
    file: symlink.yml
  #when: apt_host_pckg_lst | contains bind9
#
- name: Job 09 | import task bashrc
  ansible.builtin.import_tasks:
    file: bashrc.yml
  #when: apt_host_pckg_lst | contains bind9
#
- name: Job 10 | import task dhcp
  ansible.builtin.import_tasks:
    file: dhcp.yml
  #when: apt_host_pckg_lst | contains bind9
#
- name: Job 11 | import task myiptable
  ansible.builtin.import_tasks:
    file: myiptable.yml
  #when: apt_host_pckg_lst | contains bind9
#
- name: Job 12 | import task grafana
  ansible.builtin.import_tasks:
    file: grafana.yml
  when: instl_grafana
  tags:
    - grafana
    #- #test
#
- name: Job 13 | import task docker swarm - master
  ansible.builtin.import_tasks:
    file: swarm_master.yml
  when: instl_swrm_mstr
  tags:
    #- #test
    - swarm
#
- name: Job 14 | import task docker swarm - node
  ansible.builtin.import_tasks:
    file: swarm_node.yml
  when: instl_swrm_node
  tags:
    #- test
    - swarm
#
- name: Job 15 | import task fail2ban
  ansible.builtin.import_tasks:
    file: fail2ban.yml
  #when: apt_host_pckg_lst | contains bind9
#
- name: Job 16 | import task parted
  ansible.builtin.import_tasks:
    file: parted.yml
  when: start_prtd
  tags:
    - parted
    #- test
#
- name: Job 17 | import task rsync
  ansible.builtin.import_tasks:
    file: rsync.yml # work in progress. reman to 
  when: start_rsync and paused
  tags:
    #- test
    - rsync
##
- name: Job 18 | import task healthcheck_io
  ansible.builtin.import_tasks:
    file: healthcheck_io.yml
  #when: start_rsync and paused
  tags:
    #- test
    - healthcheck
#
- name: Job 19 | import task healthcheck_io_v2
  ansible.builtin.import_tasks:
    file: healthcheck_io_v2.yml
  #when: start_rsync and paused
  tags:
    #- test
    - healthcheck
#
# - name: Job 20 | import task accesswebpages
#   ansible.builtin.import_tasks:
#     file: accesswebpages.yml
#   #when: start_rsync and paused
#   tags:
#     - test
#     - accesswebpages
#
- name: Job 99 | import task server clean up
  ansible.builtin.import_tasks:
    file: servercleanup.yml
  when: servercleanup
  tags:
    - servercleanup
    #- test