---
# tasks file for configs
- name: Job 01 | import task anydesk
  ansible.builtin.import_tasks:
    file: anydesk.yml
#
- name: Job 05 | Copy root folder to target host that matches "ansible_hostname"
  copy:
    src: "files/{{ansible_hostname}}/root"
    dest: "/"
    owner: root
    group: root
    mode: 0700
  when: ansible_hostname != 'virthost01'
#
- name: Job 06 | import task bind
  ansible.builtin.import_tasks:
    file: bind.yml
  #when: apt_host_pckg_lst | contains bind9

- name: Job 07 | import task interfaces
  ansible.builtin.import_tasks:
    file: interfaces.yml
  #when: apt_host_pckg_lst | contains bind9
#
- name: Job 08 | import task symlink
  ansible.builtin.import_tasks:
    file: symlink.yml
  #when: apt_host_pckg_lst | contains bind9
#
- name: Job 09 | import task bashrc
  ansible.builtin.import_tasks:
    file: bashrc.yml
  #when: apt_host_pckg_lst | contains bind9
#
- name: Job 10 | import task dhcp
  ansible.builtin.import_tasks:
    file: dhcp.yml
  #when: apt_host_pckg_lst | contains bind9
#
- name: Job 10 | import task firewall
  ansible.builtin.import_tasks:
    file: firewall.yml
  #when: apt_host_pckg_lst | contains bind9