# - name: Mount mediafiles (NFS volume)
#   ansible.posix.mount:
#     src: 10.0.0.131:/mnt/Pool03-Data/mediafiles
#     path: /net/mediafiles
#     opts: rw,sync,hard
#     #state: mounted
#     state: absent
#     fstype: nfs
#   when: instl_docker_pckg and dckr_dpl_plex
#   tags:
#     - test
# #
# - name: add user to group
#   user:
#     name: ibrahim@skyline 
#     groups:  sudo, docker 
#   tags:
#     - #test  
# #
# - name: Mount ephemeral SMB volume
#   block:
#   - name: Mount ephemeral SMB volume
#     ansible.posix.mount:
#       src: //10.1.0.131/users
#       path: /net/users
#       #opts: "rw,vers=3,file_mode=0640,dir_mode=0740,dom=skyline,username=ibrahim,password={{ localhost_become_pass }}"
#       opts: "rw,vers=3,file_mode=0777,dir_mode=0777,username=ibrahim@skyline,password={{ localhost_become_pass }}"
#       #opts: "rw,vers=3,file_mode=0644,dir_mode=0744,username=root,password={{ localhost_become_pass }}"
#       fstype: cifs
#       #state: present
#       state: ephemeral
#   when: servercleanup
#   # become: false
#   # become_user: ibrahim    
#   tags:
#     - servercleanup
#
#
- name: Mount ephemeral SMB volume
  block:
  - name: Mount ephemeral SMB volume
    ansible.posix.mount:
      src: //10.1.0.131/users
      path: /net/users
      #opts: "rw,vers=3,file_mode=0640,dir_mode=0740,dom=skyline,username=ibrahim,password={{ localhost_become_pass }}"
      opts: "rw,vers=3,file_mode=0777,dir_mode=0777,username=ibrahim@skyline,password={{ localhost_become_pass }}"
      #opts: "rw,vers=3,file_mode=0644,dir_mode=0744,username=root,password={{ localhost_become_pass }}"
      fstype: cifs
      #state: present
      state: ephemeral
  when: servercleanup
  tags:
    - #servercleanup
#