---
- name: Wake on LAN Playbook
  ansible.builtin.set_fact:
    macs:
      - "00:17:08:22:a9:80" #  10.3.0.228      -NA-           2025-09-12 15:14:54 -NA-                
      - "50:7b:9d:cc:27:9b" #  10.3.0.201      L460-01        2025-09-12 14:59:37 -NA-                
      - "98:fa:9b:65:af:46" #  10.3.0.204      T480-01        2025-09-12 15:06:57 -NA-                
      - "98:fa:9b:8c:61:7d" #  10.3.0.217      T480-03        2025-09-12 14:53:18 -NA-                
      - "d4:ae:52:c9:9d:0b" #  10.3.0.205      idrac-731YXX1  2025-09-12 14:54:10 -NA-                
      - "d4:ae:52:d0:f3:89" #  10.3.0.229      idrac          2025-09-12 14:54:21 -NA-                
      - "e8:6a:64:ce:13:d8" #  10.3.0.211      T480-04        2025-09-12 15:07:24 -NA-                
      - "f8:75:a4:32:4d:13" #  10.3.0.210      T480-02        2025-09-12 14:49:35 -NA-   
    wol_broadcast: "255.255.255.255"  # or e.g., "192.168.1.255"
    wol_port: 9
#
#
# roles/wol/tasks/main.yml

# This role expects:
#   macs            - list of MAC addresses (required)
#   wol_broadcast   - broadcast address (default: 255.255.255.255)
#   wol_port        - UDP port for WOL (default: 9)

- name: Validate required inputs
  ansible.builtin.assert:
    that:
      - macs is defined
      - macs | length > 0
      - macs is iterable
    fail_msg: "Provide a non-empty list of MAC addresses via the 'macs' variable."

- name: Send Wake-on-LAN magic packets (delegated to localhost)
  ansible.builtin.wakeonlan:
    mac: "{{ item }}"
    broadcast: "{{ wol_broadcast | default('255.255.255.255') }}"
    port: "{{ wol_port | default(9) }}"
  loop: "{{ macs }}"
  delegate_to: "localhost"
  run_once: true
  tags: ['wol']
