version: '3.3'
services:
    doku:
        container_name: doku
        ports:
            - '9092:9090'
        volumes:
            - '/var/run/docker.sock:/var/run/docker.sock:ro'
            - '/:/hostroot:ro'
        restart: always
        image: amerkurev/doku