---
all:
  hosts:
    wifiboss_router:
      ansible_host: 192.168.1.123
    x86:
      ansible_host: 10.1.0.240
    vm-mtek02:
      ansible_host: 10.1.0.240
  vars:
    # ansible_user: admin
    ansible_user: ibrahim
    # ansible_password: "{{ vault_router_password }}"
    ansible_password: "{{ localhost_become_pass }}"
    ansible_connection: ansible.netcommon.network_cli
    ansible_network_os: community.routeros.routeros
    ansible_command_timeout: 60
