---
version: '3.3'
services:
    pihole:
        container_name: pihole
        ports:
            - '53:53/tcp'
            - '53:53/udp'
            - '8080:80'
        restart: always
        environment:
            - TZ=Europe/Berlin
            - VIRTUAL_HOST=pihole.zertiahmef.com
            - PROXY_LOCATION=pihole.zertiahmef.com
            - ServerIP=217.160.100.209
        volumes:
            - './docker/etc:/etc/pihole'
            - './docker/dnsmasq:/etc/dnsmasq.d'
        dns:
            - 1.1.1.1
        hostname: pihole.zertiahmef.com
        image: 'pihole/pihole:latest'