hostname_additional_hosts:
  - ip_address: 85.215.157.19
    hostname: de-1010-xl.online-server.cloud
    hostname_short: "de-1010-xl"
  # - ip_address: 5.6.7.8
  #   hostname: b.example.com
  #   hostname_short: b
#
apt_started_services_list:                # Ensure Services are running.
  - chronyd
#
### PRVS | CONFIG ###
prvs_copy_home: yes                       # Copy default user's home files in place
prvs_root_passwd: yes                     # update root passward
#
dkr_copy_def_files: no                   # Copy default docker files to target server
dkr_copy_etx_files: no                   # # Copy extended docker files to target host

crntb_activate_cronjobs: no
#
#
### APT | PACKAGES INSTALL ###
instl_def_pckg: yes                       # Install complete packages. A 'no' will remove it from the host (apt_def_pckg_lst)
instl_utl_pckg: yes                        # Install complete packages. A 'no' will remove it from the host (apt_util_lst)
sysd_strt_srvc: yes                       # Start services
instl_ansbl_pckg: no                      # Install ansible using PIP (pip_ansbl_pckg_lst apt_ansbl_pckg_lst)
instl_docker_pckg: yes                    # Install Docker package (apt_docker_pckg_lst)
apt_host_pckg_lst:                        # Install Host Specific Packages (keep this empty. use host_var to overwrite it)
dckr_fldr_lst:                            # Docker folder list that will be copied when set in the host variable
- { fldr: "4a999ff" }

crntb_fldr_lst:                            # Crontab folder list that will be copied when set in the host variable
- { fldr: "4a999ff" }

crntb_actvt_crnjbs_mrym: no
dckr_dpl_meryem: yes
dckr_dpl_anasse: yes