hostname_additional_hosts:
  - ip_address: 192.168.77.213
    hostname: gitlab.skyline.lan
    hostname_short: gitlab

#first time init
# ansible_remote_user: vagrant
# ansible_ssh_user: vagrant
# ansible_ssh_password: '{{ jenkins_become_pass }}'
# ansible_become_pass: '{{ jenkins_become_pass }}'
#
#
ansible_become_pass: '{{ localhost_become_pass }}'
#
### PRVS | CONFIG ###
prvs_copy_home: yes                       # Copy default user's home files in place
prvs_root_passwd: yes                     # update root passward
#
dkr_copy_def_files: yes                   # Copy default docker files to target server
#
crntb_activate_cronjobs: no
#
#
dckr_fldr_lst:                            # Docker folder list that will be copied when set in the host variable
- { fldr: "gitlab" }

apt_hst_strt_srvc_lst:                        # Ensure Host Specific Services are running.

#
#
### APT | PACKAGES INSTALL ###
instl_def_pckg: yes                       # Install complete packages. A 'no' will remove it from the host (apt_def_pckg_lst)
instl_utl_pckg: yes                        # Install complete packages. A 'no' will remove it from the host (apt_util_lst)
sysd_strt_srvc: yes                       # Start services
instl_ansbl_pckg: yes                      # Install ansible using PIP (pip_ansbl_pckg_lst apt_ansbl_pckg_lst)
instl_docker_pckg: yes                    # Install Docker package (apt_docker_pckg_lst)
apt_host_pckg_lst:                        # Install Host Specific Packages (keep this empty. use host_var to overwrite it)
#  - systemctl
#  - systemd