---
# vault_router_password: "CHANGE_THIS_IN_ANSIBLE_VAULT"

wifiboss_wan_interface: "WAN"
wifiboss_lan_interface: "LAN"

wifiboss_wan_address: "10.1.0.240/14"
wifiboss_lan_address: "192.168.18.1/24"
wifiboss_gateway: "10.1.0.254"

wifiboss_dns_servers:
  - "192.168.18.1"
  #- "8.8.8.8"

wifiboss_hotspot_dns_name: "wifiboss.link"
wifiboss_hotspot_profile: "WiFiBoss-HotSpot-Profile"
wifiboss_hotspot_server: "WiFiBoss-HotSpot"

wifiboss_dhcp_pool: "LAN-DHCP-POOL"
wifiboss_dhcp_range: "192.168.18.10-192.168.18.200"
wifiboss_dhcp_server: "LAN-DHCP"

# Set this to the current script URL supplied by Tikman.
tikman_setup_url: ""

# Leave false unless Tikman supplied an external RADIUS server.
tikman_configure_external_radius: false
tikman_radius_server: ""
tikman_radius_secret: ""

# Temporary local test account.
wifiboss_create_test_user: false
wifiboss_test_username: "router-test"
wifiboss_test_password: "CHANGE_THIS_TEST_PASSWORD"

# Set true only when you intentionally want the role to delete the test account.
wifiboss_remove_test_user: false

#
config: true
