---
ether1: "WAN"
ether2: "LAN"

hostname: "vm-mtek02"
ssh_user: "ibrahim"

WAN_IP: "10.1.0.240"
WAN_PREFIX: "24"

ssh_pubkey: "files/ibrahim.pub"

# Restrict SSH to this WAN subnet.
# Adjust this if your WAN network is not 10.1.0.0/24.
ssh_allowed_network: "10.0.0.0/14"

ssh: true

# sandbox/myAnsible/provisions/files/authorized_key/ibrahim.pub
