- name: Job 00 | Deploy Resume
  community.docker.docker_compose:
    #working_dir: "/opt/docker/rxresume-8662/"
    #working_dir: "{{dckr_bs_pth}}/rxresume-8662/"
    #remove_images: all
    #remove_volumes: True
    #stopped: True
    #state: absent
    #
    project_name: Resume
    definition:
      version: "3.9"
      services:
        Resume:
          image: amruthpillai/reactive-resume:v1
          container_name: Resume_con
          hostname: "https://resume{{ dmain_pstfx }}"
          user: ${UID}:${GID}
          restart: always
          ports:
            - 5050:80
  when: instl_docker_pckg and dckr_dpl_rsume
  tags:
    - assert
    - #test           
#
#
#  
# docker run -d --name=reactive_resume \
# -p 5050:80 \
# --restart always \
# amruthpillai/reactive-resume:v1