- name: Job 00 | Deploy Invidious
  community.docker.docker_compose:
    #working_dir: "/opt/docker/invidious-7601/"
    #remove_images: all
    #remove_volumes: True
    #stopped: True
    #state: absent
    #
    project_name: Invidious
    definition:
      version: '3.9'
      services:
        invidious-db:
          image: postgres
          container_name: Invidious-DB
          hostname: invidious-db
          security_opt:
            - no-new-privileges:true
          healthcheck:
            test: ["CMD", "pg_isready", "-q", "-d", "invidious", "-U", "kemal"]
            timeout: 45s
            interval: 10s
            retries: 10
          user: ${UID}:${GID}
          volumes:
            - /opt/docker/invidious-7601/invidiousdb:/var/lib/postgresql/data
          environment:
            POSTGRES_DB: invidious
            POSTGRES_USER: kemal
            POSTGRES_PASSWORD: kemalpw
          restart: always

        invidious:
          image: quay.io/invidious/invidious:latest
          container_name: Invidious
          hostname: invidious
          user: ${UID}:${GID}
          security_opt:
            - no-new-privileges:true
          healthcheck:
            test: wget -nv --tries=1 --spider http://127.0.0.1:3000/api/v1/comments/jNQXAC9IVRw || exit 1
            interval: 30s
            timeout: 5s
            retries: 2
          ports:
            - 7601:3000
          environment:
            INVIDIOUS_CONFIG: |
              db:
                dbname: invidious
                user: kemal
                password: kemalpw
                host: invidious-db
                port: 5432
              check_tables: true
              captcha_enabled: false
              default_user_preferences:
                locale: ro
                region: DE
              external_port: 443
              domain: yt.home.sawadogo.xyz
              hmac_key: e8b09fcc0882e8b646beab0135027f748c39f27acb142b339a9b199acd3b0a2b
              https_only: true
          restart: always
          depends_on:
            invidious-db:
              condition: service_started
  when: instl_docker_pckg and dckr_dpl_invdus
  tags:
    - #test              
#
#
#         youtubedl:
#           hostname: ytdl.skyline.lan
#           container_name: YoutubeDl_con
#           image: tzahi12345/youtubedl-material:latest
#           ports:
#             - 8084:17442/tcp
#           restart: always
#           environment:
#             - TZ=Europe/Berlin
#             - PUID=${UID}
#             - PGID=${GID}
#             - HTTP_USER=ibrahim
#             - HTTP_PASS={{ansible_become_pass}}
#           volumes:
#             - /opt/docker/youtubedl-8084/appdata:/app/appdata
#             - /opt/docker/youtubedl-8084/audio:/app/audio
#             - /opt/docker/youtubedl-8084/subscriptions:/app/subscriptions
#             - /opt/docker/youtubedl-8084/users:/app/users
#             - /opt/docker/youtubedl-8084/video:/app/video
#   when: instl_docker_pckg and dckr_dpl_youtubedl
#   register: output
#   tags:
#     - #test
# #
# - name: Verify that tubesync is running
#   ansible.builtin.assert:
#     that:
#       - "output.services.youtubedl.YoutubeDl_con.state.running"
#       - #"output.services.mysql.ansiblemysql.state.running"
#   when: instl_docker_pckg and dckr_dpl_youtubedl
#   tags:
#     - assert
#     - #test

# # https://mariushosting.com/how-to-install-invidious-on-your-synology-nas/

# version: "3.9"
# services:
#   invidious-db:
#     image: postgres
#     container_name: Invidious-DB
#     hostname: invidious-db
#     security_opt:
#       - no-new-privileges:true
#     healthcheck:
#       test: ["CMD", "pg_isready", "-q", "-d", "invidious", "-U", "kemal"]
#       timeout: 45s
#       interval: 10s
#       retries: 10
#     user: 1026:100
#     volumes:
#       - /volume1/docker/invidiousdb:/var/lib/postgresql/data
#     environment:
#       POSTGRES_DB: invidious
#       POSTGRES_USER: kemal
#       POSTGRES_PASSWORD: kemalpw
#     restart: always

#   invidious:
#     image: quay.io/invidious/invidious:latest
#     container_name: Invidious
#     hostname: invidious
#     user: 1026:100
#     security_opt:
#       - no-new-privileges:true
#     healthcheck:
#       test: wget -nv --tries=1 --spider http://127.0.0.1:3000/api/v1/comments/jNQXAC9IVRw || exit 1
#       interval: 30s
#       timeout: 5s
#       retries: 2
#     ports:
#       - 7601:3000
#     environment:
#       INVIDIOUS_CONFIG: |
#         db:
#           dbname: invidious
#           user: kemal
#           password: kemalpw
#           host: invidious-db
#           port: 5432
#         check_tables: true
#         captcha_enabled: false
#         default_user_preferences:
#           locale: ro
#           region: RO
#         external_port: 443
#         domain: invidious.yourname.synology.me
#         hmac_key: e8b09fcc0882e8b646beab0135027f748c39f27acb142b339a9b199acd3b0a2b
#         https_only: true
#     restart: always
#     depends_on:
#       invidious-db:
#         condition: service_started