# https://docs.ansible.com/ansible/latest/collections/community/docker/docker_stack_module.html
#
- name: Deploy stack from a compose file
  community.docker.docker_stack:
    state: present
    name: mystack
    compose:
      - #/opt/docker-compose.yml
      - portainer-agent-stack.yml

# - name: Deploy stack from base compose file and override the web service
#   community.docker.docker_stack:
#     state: present
#     name: mystack
#     compose:
#       - /opt/docker-compose.yml
#       - version: '3'
#         services:
#           web:
#             image: nginx:latest
#             environment:
#               ENVVAR: envvar

# - name: Remove stack
#   community.docker.docker_stack:
#     name: mystack
#     state: absent