---
# tasks file for dockers
- name: Job 01 | Copy default docker files to "{{ansible_hostname}}"
  copy:
    src: "files/docker"
    dest: "/opt/"
    owner: ibrahim
    group: ibrahim
    mode: 0744
  when: ansible_os_family == 'Debian' and dkr_copy_def_files # ansible_hostname != 'virthost01' or ansible_hostname != '4a999ff' 

- name: Job 02 | Copy extended docker files to target host
  copy:
    src: "files/a35a0d3/docker"
    dest: "/opt/"
    owner: ibrahim
    group: ibrahim
    mode: 0744
  when: ansible_os_family == 'Debian' and dkr_copy_etx_files # ansible_hostname == 'a35a0d3'

- name: Job 03 | Copy Specific docker folder(s) to target host
  copy:
    src: "files/{{item.fldr}}/docker"
    dest: "/opt/"
    owner: ibrahim
    group: ibrahim
    mode: 0744
  with_items:
    "{{ dckr_fldr_lst }}"
  when: dckr_fldr_lst.0 is defined

- name: Job 04 | Copy docker folder(s) to target host that matches "ansible_hostname"
  copy:
    src: "files/{{ansible_hostname}}/docker"
    dest: "/opt/"
    owner: ibrahim
    group: ibrahim
    mode: 0744
  when: ansible_hostname != 'virthost01'
#
# command: touch "{{ item.item }}"
#   with_items:
#       - { item: "1" }
#       - { item: "2" }
#       - { item: "3" }