---
# tasks file for dockers
- name: Job 01 | Copy default docker files to "{{ansible_hostname}}"
  copy:
    src: "files/docker"
    dest: "/opt/"
    owner: ibrahim
    group: ibrahim
    mode: 0744
  when: ansible_os_family == 'Debian' and dkr_copy_def_files # ansible_hostname != 'virthost01' or ansible_hostname != '4a999ff' 

- name: Job 02 | Copy extended docker files to target host
  copy:
    src: "files/a35a0d3/docker"
    dest: "/opt/"
    owner: ibrahim
    group: ibrahim
    mode: 0744
  when: ansible_os_family == 'Debian' and dkr_copy_etx_files # ansible_hostname == 'a35a0d3'

- name: Job 03 | Copy Specific docker folder(s) to target host
  copy:
    src: "files/{{item.fldr}}/docker"
    dest: "/opt/"
    owner: ibrahim
    group: ibrahim
    mode: 0744
  with_items:
    "{{ dckr_fldr_lst }}"
  when: dckr_fldr_lst.0 is defined
#
#TODO: find a way to imporve the copy - shut it down and use docker deploy
- name: Job 04 | Copy docker folder(s) to target host that matches "ansible_hostname"
  copy:
    src: "files/{{ansible_hostname}}/docker"
    dest: "/opt/"
    owner: ibrahim
    group: ibrahim
    mode: 0744
  #when: ansible_hostname != 'virthost01'
#
- name: Job 08 | import task watchtower
  ansible.builtin.import_tasks:
    file: 0000-watchtower.yml
  #when: apt_host_pckg_lst | contains bind9
#
- name: Job 09 | import task dozzle
  ansible.builtin.import_tasks:
    file: 8892-dozzle.yml
  #when: apt_host_pckg_lst | contains bind9
#
- name: Job 10 | import task iSpy
  ansible.builtin.import_tasks:
    file: 8099-iSpy.yml
  #when: apt_host_pckg_lst | contains bind9
#
- name: Job 11 | import task semaphore
  ansible.builtin.import_tasks:
    file: 3002-semaphore.yml
  #when: apt_host_pckg_lst | contains bind9
#
- name: Job 12 | import task semaphore
  ansible.builtin.import_tasks:
    file: 8081-nginx_proxy_manager.yml
  #when: apt_host_pckg_lst | contains bind9
#
- name: Job 13 | import task truecommand
  ansible.builtin.import_tasks:
    file: 3006-truecommand.yml
  #when: apt_host_pckg_lst | contains bind9
#
- name: Job 14 | import task pihole
  ansible.builtin.import_tasks:
    file: 8080-pihole.yml
  #when: apt_host_pckg_lst | contains bind9
#
- name: Job 15 | import task gravity
  ansible.builtin.import_tasks:
    file: 8008-gravity.yml
  #when: apt_host_pckg_lst | contains bind9
#
- name: Job 16 | import task homepage
  ansible.builtin.import_tasks:
    file: 3550-homepage.yml
  #when: apt_host_pckg_lst | contains bind9
#
- name: Job 17 | import task plex
  ansible.builtin.import_tasks:
    file: 32400-plex.yml
  #when: apt_host_pckg_lst | contains bind9
#
- name: Job 18 | import task tubesync
  ansible.builtin.import_tasks:
    file: 4848-tubesync.yml
  #when: apt_host_pckg_lst | contains bind9
#
- name: Job 19 | import task YoutubeDl
  ansible.builtin.import_tasks:
    file: 8084-youtubedl.yml
  #when: apt_host_pckg_lst | contains bind9
#
- name: Job 20 | import task opensubtitles
  ansible.builtin.import_tasks:
    file: 0000-opensubtitles.yml
  #when: apt_host_pckg_lst | contains bind9
#
- name: Job 21 | import task tautulli
  ansible.builtin.import_tasks:
    file: 8181-tautulli.yml
  #when: apt_host_pckg_lst | contains bind9
#
- name: Job 22 | import task overseerr
  ansible.builtin.import_tasks:
    file: 5055-overseerr.yml
  #when: apt_host_pckg_lst | contains bind9
#
- name: Job 23 | import task emby
  ansible.builtin.import_tasks:
    file: 8096-emby.yml
  #when: apt_host_pckg_lst | contains bind9
#
- name: Job 24 | import task invidious
  ansible.builtin.import_tasks:
    file: 7601-invidious.yml
  #when: apt_host_pckg_lst | contains bind9
#
- name: Job 25 | import task rxresume
  ansible.builtin.import_tasks:
    file: 8662-rxresume.yml
  #when: apt_host_pckg_lst | contains bind9
#
- name: Job 26 | import task resume
  ansible.builtin.import_tasks:
    file: 5050-resume.yml
  #when: apt_host_pckg_lst | contains bind9
#
- name: Job 27 | import task resume
  ansible.builtin.import_tasks:
    file: 3555-wud.yml
  #when: apt_host_pckg_lst | contains bind9
#
- name: Job 28 | import task webpdf
  ansible.builtin.import_tasks:
    file: 25568-webpdf.yml
  #when: apt_host_pckg_lst | contains bind9
#
- name: Job 29 | import task stirling-pdf
  ansible.builtin.import_tasks:
    file: 25568-stirling-pdf.yml
  #when: apt_host_pckg_lst | contains bind9
#
- name: Job 30 | import task meryem
  ansible.builtin.import_tasks:
    file: 8090-meryem.yml
  when: instl_docker_pckg and dckr_dpl_meryem
  tags:
    - meryem
    - #test  
#
- name: Job 31 | import task anasse
  ansible.builtin.import_tasks:
    file: 8090-meryem.yml
  when: instl_docker_pckg and dckr_dpl_anasse
  tags:
    - anasse
    - #test  
#
#
#
# keep this last
- name: Job 99 | import task prune
  ansible.builtin.import_tasks:
    file: prune.yml
  when: instl_docker_pckg
  tags:
    - prune
    - #test
#
# command: touch "{{ item.item }}"
#   with_items:
#       - { item: "1" }
#       - { item: "2" }
#       - { item: "3" }
